fix missing "then" in if statement

diff --git a/create_vm b/create_vm
--- a/create_vm
+++ b/create_vm
@@ -23,18 +23,18 @@ echo -en "FQDN. default ${VM_NAME}.$DOMAIN : "
 read FQDN ; if [[ -z $FQDN ]] ; then FQDN=${VM_NAME}.$DOMAIN ; fi
 
 echo -en "Enter IP Address, must be valid IP: "
-read IP_ADDRESS ; if ipcalc -c $IP_ADDRESS 2>/dev/null ; echo "IP_ADDRESS: $IP_ADDRESS" ; else echo "$IP_ADDRESS invalid IP adress" ; exit 1 ; fi
+read IP_ADDRESS ; if ipcalc -c $IP_ADDRESS 2>/dev/null ; then echo "IP_ADDRESS: $IP_ADDRESS" ; else echo "$IP_ADDRESS invalid IP adress" ; exit 1 ; fi
 
 echo -en "Enter Netmask, default 255.255.255.0: "
 read CHANGE_NETMASK ; if [[ -z $CHANGE_NETMASK ]] ; then CHANGE_NETMASK=255.255.255.0 ; fi
 
 echo -en "Enter GW, default $CHANGE_GATE_DEFAULT: "
 read CHANGE_GATE ; if [[ -z $CHANGE_GATE ]] ; then CHANGE_GATE=$CHANGE_GATE_DEFAULT ; fi
-if ipcalc -c $CHANGE_GATE 2>/dev/null ; echo "Default GW: $CHANGE_GATE" ; else echo "$CHANGE_GATE invalid IP adress" ; exit 1 ; fi
+if ipcalc -c $CHANGE_GATE 2>/dev/null ; then echo "Default GW: $CHANGE_GATE" ; else echo "$CHANGE_GATE invalid IP adress" ; exit 1 ; fi
 
 echo -en "Enter DNS, default $CHANGE_NS_DEFAULT: "
 read CHANGE_NS ; if [[ -z $CHANGE_NS ]] ; then CHANGE_NS=$CHANGE_NS_DEFAULT ; fi
-if ipcalc -c $CHANGE_NS 2>/dev/null ; echo "DNS: $CHANGE_NS" ; else echo "$CHANGE_NS invalid IP adress" ; exit 1 ; fi
+if ipcalc -c $CHANGE_NS 2>/dev/null ; then echo "DNS: $CHANGE_NS" ; else echo "$CHANGE_NS invalid IP adress" ; exit 1 ; fi
 
 
 sudo /bin/cp -f /srv/vm_ks_template.ks ${WWW_LOCATION}/vm_ks.ks
